Repository gmlc-dispatches/dispatches, pull requests merged in 2021-05, with the labels that each got.

#33 Adding a logo, favicon and version to Sphinx docs
  .gitignore
  docs/_static/favicon.ico
  docs/conf.py
  docs/images/dispatches_logo-darkbg.svg
  docs/images/dispatches_logo-lightbg.svg
  docs/images/dispatches_logo_only.svg
Labels: Priority:Normal

#37 Battery
  dispatches/models/renewables_case/battery.py
  dispatches/models/renewables_case/test_battery.py
Labels: Priority:Normal

#39 Electrical Splitter
  dispatches/models/renewables_case/elec_splitter.py
  dispatches/models/renewables_case/pem_electrolyzer.py
  dispatches/models/renewables_case/test_elec_splitter.py
  dispatches/models/renewables_case/test_pem_electrolyzer.py
Labels: Priority:Normal, unit model

#38 Ultra-supercritical power plant model
  dispatches/models/fossil_case/ultra_supercritical_plant/pfd_ultra_supercritical_pc.svg
  dispatches/models/fossil_case/ultra_supercritical_plant/test_usc_powerplant.py
  dispatches/models/fossil_case/ultra_supercritical_plant/ultra_supercritical_powerplant.py
Labels: Priority:Normal

#36 Wind model and test
  dispatches/models/renewables_case/test_wind_power.py
  dispatches/models/renewables_case/wind_power.py
  requirements.txt
Labels: Priority:Normal

#42 Stubbing out the doc structure for several new models.
  .readthedocs.yaml
  docs/_static/custom.css
  docs/conf.py
  docs/copyright.rst
  docs/index.rst
  docs/license.rst
  docs/models/fossil/ccs.rst
  docs/models/fossil/concrete_thermal_storage.rst
  docs/models/fossil/existing_power_plant.rst
  docs/models/fossil/index.rst
  docs/models/fossil/molten_salt.rst
  docs/models/fossil/thermal_oil.rst
  docs/models/fossil/ustg.rst
  docs/models/index.rst
  docs/models/nuclear/hydrogen_tank.rst
  docs/models/nuclear/hydrogen_turbine.rst
  docs/models/nuclear/index.rst
  docs/models/nuclear/pem_electrolyzer.rst
  docs/models/renewables/electricity_splitter.rst
  docs/models/renewables/index.rst
  docs/models/renewables/lithium_ion_battery.rst
  docs/models/renewables/wind_turbine.rst
Labels: Priority:High, documentation
