Repository gmlc-dispatches/dispatches, pull requests merged in 2021-07, with the labels that each got.

#46 adding pytest marker list and ignoring pytest logs in gitignore
  .gitignore
  dispatches/models/nuclear_case/unit_models/test_hydrogen_tank.py
  pytest.ini
Labels: Priority:Normal

#30 Heat Exchanger No shell
  dispatches/models/fossil_case/concrete_tube/heat_exchanger_tube.py
  dispatches/models/fossil_case/concrete_tube/test_heat_exchanger_tube.py
Labels: Priority:Normal

#40 Adding supercritical powerplant flowsheet with thermal oil storage
  .gitignore
  dispatches/models/fossil_case/thermal_oil/supercritical_powerplant_simple_helm_2_charge.py
Labels: Priority:Normal, unit model

#49 Streamline installation procedure and GitHub Actions workflow
  .github/workflows/checks.yml
  .github/workflows/python-package.yml
  .readthedocs.yaml
  README.md
  docs/getting_started/index.rst
  docs/getting_started/install.rst
  docs/index.rst
  requirements-dev.txt
  requirements.txt
  setup.py
Labels: Priority:High

#48 Docs for Renewable Energy Models
  dispatches/models/renewables_case/wind_power.py
  docs/conf.py
  docs/models/renewables/battery.rst
  docs/models/renewables/electrical_splitter.rst
  docs/models/renewables/electricity_splitter.rst
  docs/models/renewables/index.rst
  docs/models/renewables/lithium_ion_battery.rst
  docs/models/renewables/pem_electrolyzer.rst
  docs/models/renewables/wind_power.rst
  docs/models/renewables/wind_turbine.rst
Labels: Priority:High
