Repository gmlc-dispatches/dispatches, pull requests merged in 2023-06, with the labels that each got.

#201 Update RAVEN and TEAL optional dependencies to May 2023 releases
  setup.py
Labels: Priority:Normal, RAVEN, TEAL, dependencies

#142 Add steady state surrogates code
  dispatches/case_studies/simple_rankine_cycle/__init__.py
  dispatches/case_studies/simple_rankine_cycle/keras_models/models/keras_nstartups/saved_model.pb
  dispatches/case_studies/simple_rankine_cycle/keras_models/models/keras_nstartups/variables/variables.data-00000-of-00001
  dispatches/case_studies/simple_rankine_cycle/keras_models/models/keras_nstartups/variables/variables.index
  dispatches/case_studies/simple_rankine_cycle/keras_models/models/keras_revenue/saved_model.pb
  dispatches/case_studies/simple_rankine_cycle/keras_models/models/keras_revenue/variables/variables.data-00000-of-00001
  dispatches/case_studies/simple_rankine_cycle/keras_models/models/keras_revenue/variables/variables.index
  dispatches/case_studies/simple_rankine_cycle/keras_models/models/keras_zones/saved_model.pb
  dispatches/case_studies/simple_rankine_cycle/keras_models/models/keras_zones/variables/variables.data-00000-of-00001
  dispatches/case_studies/simple_rankine_cycle/keras_models/models/keras_zones/variables/variables.index
  dispatches/case_studies/simple_rankine_cycle/keras_models/models/training_parameters_nstartups.json
  dispatches/case_studies/simple_rankine_cycle/keras_models/models/training_parameters_revenue.json
  dispatches/case_studies/simple_rankine_cycle/keras_models/models/training_parameters_zones.json
  dispatches/case_studies/simple_rankine_cycle/simple_rankine_cycle.py
  dispatches/case_studies/simple_rankine_cycle/surrogate_design_alamo.py
  dispatches/case_studies/simple_rankine_cycle/surrogate_design_keras.ipynb
  dispatches/case_studies/simple_rankine_cycle/surrogate_design_scikit.py
  dispatches/case_studies/simple_rankine_cycle/train_alamo_surrogates.py
  dispatches/case_studies/simple_rankine_cycle/train_keras_surrogates.py
  dispatches/case_studies/simple_rankine_cycle/train_scikit_surrogates.py
  dispatches/util/__init__.py
  dispatches/util/surrogates.py
Labels: Priority:High

#206 Add more tests to dynamic surrogates
  dispatches/workflow/train_market_surrogates/dynamic/Time_Series_Clustering.py
  dispatches/workflow/train_market_surrogates/dynamic/Train_Market_Surrogates.ipynb
  dispatches/workflow/train_market_surrogates/dynamic/Train_NN_Surrogates.py
  dispatches/workflow/train_market_surrogates/dynamic/tests/test_Simulation_Data.py
  dispatches/workflow/train_market_surrogates/dynamic/tests/test_Time_Series_Clustering.py
  dispatches/workflow/train_market_surrogates/dynamic/tests/test_Train_NN_Surrogates.py
Labels: Priority:Normal
